class UserNotFoundError(Exception):
    pass


class CRUDError(Exception):
    pass
